### ISSUE TITLE
PyPi and Conda-Forge Packages?

### ISSUE THREAD

**Issue by ghutchis** [Boehringer-Ingelheim/pyPept#1]
This looks great. Would it be possible to submit this as a package to pypi and/or conda for installs?

If you submit to pypi, I can easily put together the conda-forge package. (That part is easy if it's on PyPI .. it just takes a bit before it's approved on conda-forge.)

One or both would make it much easier to install as part of other workflows.

**Comment by marcostenta** [comment]
Hi Folks, having it as a package would really help. I can make a pull request with a packaged version of it: no change to the code just re-shaped as a molssi python package cookie cutter template . would it be OK with the authors to review the pull request? this would make it easier to push to pypi and possibly conda-forge

**Comment by marcostenta** [comment]
Hi, let me share the fork I just created at the link below
https://github.com/syngenta/pyPept

it installs as 

pip install git+https://github.com/syngenta/pyPept.git

there is basically no change to the code, except the ones to read the necessary files (sdf and txt) in the data folder, this also allows removing the deprecated pkg library
the new installer takes care of creating the command line interface and placing them in the virtual environment, so that once the package is installed, the CLIs are in the path and immediately available.
the doc section is created and mostly empty but working. it is compatible with readthedocs 
i added some usual configuration files for linting, but did not apply them
I also added in the toml file the configuration for bumpver, a nice tool to help with semantic versioning, aligned with git tags
in this shape it is ready or very close  for pypi submission

please have a look, and if you are OK I can file a pull request

Overall, this package is great work: we are starting to use it, and I would be happy to make it easier to install and operate. 
Always happy to discuss further.

**Comment by ghutchis** [comment]
I would also be happy to help. Going from a PyPi submission to condo-forge is trivial and I'd be happy to do that part.

We've been using this with Avogadro2 and it's very helpful to my research group.

**Comment by foxth** [comment]
Hi,
first of all - sorry for not responding earlier, the last weeks were too busy. And then thanks that you find our package useful - this is exactly why we put it out there.

Our initial reason not to package pypept via pip or conda is that - at least in my eyes - this would imply a level of support that we probably cannot guarantee (my late response is witness to that). But if this makes things much easier for folks, I will not want to be in the way either. Ill review the pull request then.

Best,
Th.
